name: remote ssh command
on: [push]
jobs:




  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: show ip
      - run: echo host myip.opendns.com resolver1.opendns.com


  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: whoami
